### PR TITLE
do terrible things to 'got add'

### PR DESCRIPTION
**Pull request by yanick**
* Allow to pass more than one directory as arguments.

* add '--recursive', to hunt down git repos under a main directory.

* make '--tag X' set the default tag(s) to X

* If there's only one remote, don't ask, use that one.

* Instead of asking the user to type the remote uri, give the choice between the remote name/url pairs.

### CODE REVIEW

**Comment by yanick** [comment]
I sliced the commit into semi-independent parts. They are not absolutely independent of each other, but they should make for an easier diff reading.

**Comment by genehack** [comment]
Thanks again for carving those commits up, I feel a lot better about this commit now. (I'm a little leary of `maybe`, but I'm going to trust you...)

I grabbed your branch, squished everything back into a single commit, applied some formatting and minor code organization/logic tweaks to it, rebased on the current master, and pushed to a branch in my repo ('got-add-multi-add' @ 435f61ba2987e0a1b755f6d7b11ac7cba1f82975)

Everything looks great, _except_ tests are failing >_< Here's what I see:

```
% prove -l                                                                                                                                                                                             got-add-multi-add •  18:56:09
t/01-run.t ..... ok
t/02-add.t ..... 1/?
#   Failed test 'nothing on stdout'
#   at t/02-add.t line 35.
#          got: '
# Add repository at '/private/var/folders/gd/n6xwfsjd0dzcngcyp60cxvth0000gn/T/3XCR3qF2HM/foo.git'?  (y/n) [y]: y
# Name?  [foo.git]: foo.git
# Tracking remote?  :
# Tags?  []:
# '
#     expected: ''

#   Failed test 'nothing on stderr'
#   at t/02-add.t line 36.
#          got: '-f on unopened filehandle STDOUT at /opt/plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/IO/Prompt/Simple.pm line 208.
# -c on unopened filehandle STDOUT at /opt/plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/IO/Prompt/Simple.pm line 208.
# -f on unopened filehandle STDOUT at /opt/plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/IO/Prompt/Simple.pm line 208.
# -c on unopened filehandle STDOUT at /opt/plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/IO/Prompt/Simple.pm line 208.
# -f on unopened filehandle STDOUT at /opt/plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/IO/Prompt/Simple.pm line 208.
# -c on unopened filehandle STDOUT at /opt/plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/IO/Prompt/Simple.pm line 208.
# -f on unopened filehandle STDOUT at /opt/plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/IO/Prompt/Simple.pm line 208.
# -c on unopened filehandle STDOUT at /opt/plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/IO/Prompt/Simple.pm line 208.
# '
#     expected: ''

#   Failed test 'exit with 0'
#   at t/02-add.t line 37.
#          got: '-1'
#     expected: '0'
# File [/var/folders/gd/n6xwfsjd0dzcngcyp60cxvth0000gn/T/3XCR3qF2HM/gitgot] does not exist

#   Failed test 'config exists'
#   at t/02-add.t line 39.
YAML Error: Couldn't open /var/folders/gd/n6xwfsjd0dzcngcyp60cxvth0000gn/T/3XCR3qF2HM/gitgot for input:\n
   Code: YAML_LOAD_ERR_FILE_INPUT
 at /opt/plenv/versions/5.20.0/lib/perl5/site_perl/5.20.0/YAML.pm line 70.
cannot remove path when cwd is /private/var/folders/gd/n6xwfsjd0dzcngcyp60cxvth0000gn/T/3XCR3qF2HM/foo.git for /private/var/folders/gd/n6xwfsjd0dzcngcyp60cxvth0000gn/T/3XCR3qF2HM:  at /opt/plenv/versions/5.20.0/lib/perl5/5.20.0/File/Temp.pm line 784.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 8.
t/02-add.t ..... Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 4/8 subtests
t/03-chdir.t ... ok
t/04-clone.t ... ok
t/05-fork.t .... ok
t/06-list.t .... ok
t/07-remove.t .. ok
t/08-status.t .. ok
t/09-update.t .. ok
t/10-gc.t ...... ok
t/11-push.t .... ok
t/12-fetch.t ... ok

Test Summary Report
-------------------
t/02-add.t   (Wstat: 65280 Tests: 8 Failed: 4)
  Failed tests:  5-8
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=12, Tests=135,  3 wallclock secs ( 0.06 usr  0.02 sys +  2.88 cusr  0.83 csys =  3.79 CPU)
Result: FAIL
```

If you could clean that up and maybe add a test or two for the recursive functionality, I'm happy to merge this.

**Comment by yanick** [comment]
> (I'm a little leary of maybe, but I'm going to trust you...)

You fool. ;-) Admittedly,  `maybe` is not vital, just a sprinkling of sugar.  But I find

    $foo->bar( x => 1, maybe y => $value )

much less awkward than 

    $foo->bar( x => 1, $value ? ( y => $value ) : () )

> [failing tests] 

Ooops. I'm on it.

**Comment by genehack** [comment]
Merged (a while back, actually...)

**Pull request closed without merging**
