### PR TITLE
use List::Util instead of List::AllUtils+List::MoreUtils

### PR DESCRIPTION
**Pull request by karenetheridge**

### CODE REVIEW

**Comment by genehack** [comment]
@karenetheridge - I would love to get rid of the LMU dep, but not so much that I want to have `uniq` re-implemented in my code base. As soon as there is a `List::Utils::uniq` (or as soon as my annoyance with LMU approaches the level of your own...), then I could see merging this. I'm just not there yet.

**Comment by karenetheridge** [comment]
np, you're on my list of patches when there is a "real" uniq implementation :)

**Comment by karenetheridge** [comment]
There is now a real uniq! patch updated.

**Comment by karenetheridge** [comment]
(I can't reopen the PR myself though..) :/

**Comment by genehack** [comment]
Oddly, I can't reopen the PR either. 8^/ Could you try renaming the branch or something?

**Comment by karenetheridge** [comment]
coming right up!

**Pull request closed without merging**
